server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        # RUTA 1: LOGIN & REGISTER (Sunt publice, nu cerem token)
        - id: auth-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/users/login, /api/users/register, /api/users/verify, /api/users/resend-code

        - id: auth-service-protected
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@userKeyResolver}"

        # RUTA 2: CATALOG (Stadioane, Meciuri) - Partea publică e liberă, partea de admin e protejată
        - id: catalog-public
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/stadiums/**, /api/catalog/matches/**, /api/catalog/seats/**
            - Method=GET

        - id: catalog-admin
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/stadiums/**, /api/catalog/matches/**
            - Method=POST, PATCH, DELETE
          filters:
            - AuthenticationFilter # Doar adminii (sau userii logați) pot crea stadioane/meciuri
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@userKeyResolver}"


        # RUTA 3: TICKETING - Partea pentru USER (Buy, Confirm, My Tickets)
        - id: ticketing-user
          uri: lb://TICKETING-SERVICE
          predicates:
            - Path=/api/ticketing/buy, /api/ticketing/confirm, /api/ticketing/user/**
          filters:
            - AuthenticationFilter

        # RUTA 4: TICKETING - Partea pentru ADMIN (Validate, Get All, Match Stats)
        - id: ticketing-admin
          uri: lb://TICKETING-SERVICE
          predicates:
            - Path=/api/ticketing/validate/**, /api/ticketing/match/**, /api/ticketing
          filters:
            - AuthenticationFilter
            # Aici am putea adăuga un filtru de RoleCheck dacă filtrul tău de auth suportă asta

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**


app:
  jwt:
    secret: ${ARENA_JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
