server:
  port: 8080

spring:
  data:
    redis:
      host: redis-cache
      port: 6379
      database: 0
  cloud:
    gateway:
      routes:
        # RUTA 1: LOGIN & REGISTER (Protecție Brute Force - Limită Mică)
        - id: auth-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/users/login, /api/users/register, /api/users/verify, /api/users/resend-code
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1   # 1 cerere pe secundă (aprox 60/min)
                redis-rate-limiter.burstCapacity: 3   # Maxim 3 cereri instant
                key-resolver: "#{@userKeyResolver}"

        # Acces intern pentru email-uri
        - id: auth-internal-emails
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/users/emails


        - id: auth-service-protected
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@userKeyResolver}"


        # RUTA 2: CATALOG PUBLIC (Navigare rapidă - Limită Mare)
        - id: catalog-public
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/stadiums/**, /api/catalog/matches/**, /api/catalog/seats/**
            - Method=GET
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20  # 20 cereri pe secundă
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@userKeyResolver}"

        - id: catalog-admin
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/stadiums/**, /api/catalog/matches/**
            - Method=POST, PATCH, DELETE, PUT
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@userKeyResolver}"

        # RUTA 3: TICKETING BUY (Prevenire Boți - Limită Medie)
        - id: ticketing-user
          uri: lb://TICKETING-SERVICE
          predicates:
            - Path=/api/ticketing/buy, /api/ticketing/confirm, /api/ticketing/user/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2   # 2 cereri pe secundă (destul pentru un om)
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@userKeyResolver}"

        # RUTA 4: TICKETING ADMIN
        - id: ticketing-admin
          uri: lb://TICKETING-SERVICE
          predicates:
            - Path=/api/ticketing/validate/**, /api/ticketing/match/**, /api/ticketing, /api/ticketing/analytics/**
          filters:
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

        - id: ticketing-availability
          uri: lb://TICKETING-SERVICE
          predicates:
            - Path=/api/ticketing/occupied-seats
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50  # Limită mare, fiind interogare frecventă
                redis-rate-limiter.burstCapacity: 100
                key-resolver: "#{@userKeyResolver}"


        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

app:
  jwt:
    secret: ${ARENA_JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/