server:
  port: 8084

spring:
  application:
    name: notification-service
  mail:
    host: smtp.sendgrid.net
    port: 2525
    from: ${EMAIL_USER}
    username: apikey
    password: ${SENDGRID_API_KEY}
    properties:
      # Aici era greșeala: nu mai trebuie "mail:" încă o dată
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus