server:
  port: 8083

spring:
  application:
    name: ticketing-service
  cache:
    type: redis
    redis:
      time-to-live: 600000
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
  datasource:
    url: jdbc:postgresql://localhost:5432/arena_ticketing_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      notificationCB:
        slidingWindowSize: 10 # Se uită la ultimele 10 apeluri
        failureRateThreshold: 50 # Dacă 5 din 10 eșuează, "sare" siguranța (Open)
        waitDurationInOpenState: 10s # Cât timp stă blocat înainte să încerce iar
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.arena.ticketing.exception.TicketException

      catalogCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s # Stă închis 10 secunde dacă Catalog e picat
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - com.arena.ticketing.exception.TicketException
  retry:
    instances:
      notificationRetry:
        maxAttempts: 3 # Încearcă de 3 ori înainte să renunțe
        waitDuration: 2s # Așteaptă 2 secunde între încercări