spring:
  application:
    name: arena-ticketing
  profiles:
    active: dev
  main:
    banner-mode: "off"
  mail:
    host: smtp.gmail.com
    port: 587
    username: razvancaruntu15@gmail.com
    password: fkoj zxxg pldg cwvt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081