server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          enabled: false
        native:
          # Aici folosim doar calea din container (Docker)
          search-locations: file:///app/config

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/