name: Arena Ticketing CI

on:
  push:
    branches: [ dev ]

jobs:
  build-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, auth-service, catalog-service, ticketing-service, notification-service]

    steps:
      - name: Checkout cod
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build și Test pentru ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: mvn clean package -DskipTests=false